@startuml
title TaskBoard-Mini

package "View" {
  class EventHandlers
  class DrawProcessors
  EventHandlers <-- DrawProcessors
}

package "ViewModel" {
  EventHandlers <-- ViewModelManager

  class Task {
    id
    type
  }
  class State
  interface ViewModelManager
  class ViewModelManagerImpl
  class ViewTaskManager
  ViewModelManager <|.. ViewModelManagerImpl
  ViewModelManagerImpl <|-- ViewTaskManager
  ViewTaskManager o-- TaskBoard
  TaskBoard o-- TaskList
  TaskList o-- Task
  Task o-- State
}

' ViewTaskManager --> ModelManager

package "Model" {
  class ThreadExecutor
  ViewModelManagerImpl <-- ThreadExecutor
  ThreadExecutor o-- ModelManagerFactory
  ThreadExecutor <-- ModelManager

  interface ModelManager
  interface ModelManagerFactory
  interface ModelDto
  class ModelManagerImpl
  class TaskManager
  class TaskManagerFactory
  class TaskDto
  ModelManager <|.. ModelManagerImpl
  ModelManagerImpl <|-- TaskManager
  ModelManagerFactory <|.. TaskManagerFactory
  ModelDto <|.. TaskDto
  TaskManager <-- TaskDto
  ModelManagerImpl <-- ModelDto
  TaskManagerFactory --> TaskManager : create

  ModelManagerImpl o-- DataSourceConnector
  ModelManagerImpl o-- FileAccessorFactory
  DbConnectorAdapter <-- ModelDto

  interface DataSourceConnector
  class DbConnectorAdapter
  class IndexedDbConnector
  DataSourceConnector <|.. DbConnectorAdapter
  DbConnectorAdapter o-- IndexedDbConnector

  FileAccessor --> ModelManagerImpl

  interface FileAccessorFactory
  class FileAccessorFactoryImpl
  interface FileWriter
  interface FileLoader
  interface FileAccessor
  FileAccessorFactory <|.. FileAccessorFactoryImpl
  FileAccessorFactoryImpl --> FileAccessorImpl : create
  FileAccessor <|.. FileAccessorImpl
  FileAccessorImpl o-- FileWriter
  FileAccessorImpl o-- FileLoader
  FileWriter <|.. CsvFileWriter
  FileWriter <|.. JsonFileWriter
  FileLoader <|.. JsonFileLoader
}
@enduml
